### ISSUE TITLE
optimization suggestions

### ISSUE THREAD

**Issue by GregorB54321** [CloudHustlers/Monsoon_Week_4_Skill_Badges#1]
Hi!
I am analyzing your solution approach...

- for my documentation I added some section-marks where each Task is starting...
- Task 1 can be more tidy with: 
  ```bash
  mkdir -p ~/modules/{instances,storage}
  touch ~/{main,variables}.tf
  touch ~/modules/instances/{instances,variables,outputs}.tf
  touch ~/modules/storage/{storage,variables,outputs}.tf
  ```
- it was a little difficult to understand, that code eleminations were done by complete redefinition. for adding and removing code segments you could add with
   ```bash
  echo "\
  #startLabel
  <code>
  #endLabel" \
  >> file.tf
  ```
  and later remove it by deleting lines in between the labels with `sed '/^#startLabel$/,/^#endLabel$/d'`

**Comment by CodingWithHardik** [comment]
for which lab ?

**Comment by GregorB54321** [comment]
GSP345

**Comment by siddharth7000** [comment]
Thank you @GregorB54321 
We will update it soon

**Comment by CodingWithHardik** [comment]
@siddharth7000 any update regarding this ?

**Comment by CodingWithHardik** [comment]
As there is no response from our team we are closing it
Thanks For this suggestion
