### ISSUE TITLE
Need to change zone in #GSP342

### ISSUE THREAD

**Issue by SwarnadeepGhosh** [CloudHustlers/Monsoon_Week_4_Skill_Badges#2]
Lab : 03_Ensure Access & Identity in Google Cloud/08_Ensure Access & Identity in Google Cloud: Challenge Lab #GSP342 .md

**Comment by SwarnadeepGhosh** [comment]
Change zone to us-west1-c

**Comment by CodingWithHardik** [comment]
Thanks for opening the issue we will check and revert back to you soon

**Comment by CodingWithHardik** [comment]
issue has been resolved.
